apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ticketing-lab.fullname" . }}-db-pvc
  labels:
    {{- include "ticketing-lab.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
