apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-lab.fullname" . }}-db
  labels:
    {{- include "ticketing-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ticketing-lab.selectorLabels" . | nindent 4 }}
    component: db
  ports:
    - port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
