apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticketing-lab.fullname" . }}-db-secret
  labels:
    {{- include "ticketing-lab.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.dbCredentials.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.dbCredentials.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.dbCredentials.database | b64enc | quote }}
