apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-lab.fullname" . }}-nginx
  labels:
    {{- include "ticketing-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "ticketing-lab.selectorLabels" . | nindent 4 }}
    component: nginx
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.containerPort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
