{
 "title": "DevOps Ticketing Lab - Application Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Time → milliseconds (ms)" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum[1m])) / sum(rate(flask_http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(   sum(rate(flask_http_request_total{status=~\"4..|5..\"}[1m]))   /   sum(rate(flask_http_request_total[1m])) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}