apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ticketing-lab
type: Opaque
data:
  POSTGRES_USER: dGlja2V0dXNlcg==
  POSTGRES_PASSWORD: UEBzc3cwcmQ=
  POSTGRES_DB: dGlja2V0ZGI=
